#!/usr/bin/env bash
#The script displays numbers from 1 to 100
num=1
while [ $num -lt 101 ]
do
    if [ $((num%5)) -eq 0 ] && [ $((num%3)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((num%5)) -eq 0 ]
    then
        echo "Buzz"
    elif [ $((num%3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo $num
    fi
    ((num++))
done
